# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f69e40734347561f7949e47d5e54b537044376fd390850ff2906ce98d3a9086b81e92e20c89d59f8a91ca4a1b8fad3c92b3de03caf127b2e4ae88ab102b26e86

test:
  secret_key_base: 00af266ce392634d3ed63a0032ade8ea861e8235b476f4d142b9cb42ff775e5522ef69aacc488e16796f51bcb97558e129848fed6fb26159782facf91887c6dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
